# Generated by Django 4.2 on 2023-04-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "name": {"max_length": "The price must be between 0 and 999.99."}
                },
                help_text="Maximum 999.99",
                max_digits=5,
                verbose_name="Discount price",
            ),
        ),
    ]
