# Generated by Django 4.2 on 2023-04-05 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_alter_product_discount_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productspecificationvalue",
            options={
                "verbose_name": "Product Specification Value",
                "verbose_name_plural": "Product Specification Values",
            },
        ),
        migrations.AlterModelOptions(
            name="producttype",
            options={
                "verbose_name": "Product Type",
                "verbose_name_plural": "Product Types",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="users_wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="user_wishlist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Please add alturnative text",
                max_length=255,
                null=True,
                verbose_name="Alturnative text",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="images/default.png",
                help_text="Upload a product image",
                upload_to="images/",
                verbose_name="image",
            ),
        ),
    ]
